### ISSUE TITLE
Input error in Excel not detected, causing incorrect data in calculator

### ISSUE THREAD

**Issue by brakf** [frumania/aws-pricing-calculator-scripts-test#1]
#### Error Description:
If no IOPS are provided for io2 volumes, automatically the importer uses GP2 volumes.

#### Expected behaviour:
Expected behaviour would be an error message after pasting the table.

#### Example:
![image](https://user-images.githubusercontent.com/10106543/112118237-70f2b980-8bbc-11eb-8842-e40addc03b46.png)
The first entry uses the correct volume type during import. The second does not:

![image](https://user-images.githubusercontent.com/10106543/112118422-a5667580-8bbc-11eb-9bb1-64de5c5cf703.png)
(Please note that the ordering is reversed. Another bug that needs fixing).

If you'd like me to check in the code myself, feel free to make the application repo accessible to me ;) Posting this question in this repo as it is linked in the application.

Thanks for the nice tool, Marcel!

**Comment by frumania** [comment]
I added a validation for io1/io2, but yes gp2 is fallback.
But honestly It is not foreseen to validate all possible combinations. This is an expert tool after all.

@Order:
Does not matter, does it?
